services:
  deb-ppa-upload:
    image: gitmachete/ci-deb-ppa-upload:${DIRECTORY_HASH:-unspecified}
    platform: linux/amd64
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
    volumes:
      # Host path is relative to current directory, not build-context
      - ./../..:/git-machete/mount/
    environment:
      - DO_DPUT
      - GPG_EMAIL
      - GPG_USERNAME
      - LAUNCHPAD_USERNAME
      - TARGET_DISTRO_NAME
      - TARGET_DISTRO_NUMBER
    env_file:
      - gpg-ssh.env
